highlighter: kramdown
kramdown:
  syntax_highlighter_opts:
    disable : true
collections:
  s:
    output: true
  bin:
    output: true
  prj:
    output: true

defaults:
  -
    scope:
      path: ""
      type: "prj"
    values:
      layout: "default"
