highlighter: kramdown
excerpt_separator: '====='
kramdown:
  syntax_highlighter_opts:
    disable : true

url: "https://bubujka.org"
plugins:
  - jekyll-sitemap

collections:
  snippet:
    output: true
  bin:
    output: true
  prj:
    output: true
  tech:
    output: true

defaults:
  - scope:
      path: ""
      type: "prj"
    values:
      layout: "default"
      comments: true
  - scope:
      path: ""
      type: "tech"
    values:
      layout: "default"
      comments: true
  - scope:
      path: ""
      type: "snippet"
    values:
      layout: "snippet"
      comments: true

