highlighter: kramdown
excerpt_separator: '====='
kramdown:
  syntax_highlighter_opts:
    disable : true

url: "https://bubujka.org"
plugins:
  - jekyll-sitemap

collections:
  s:
    output: true
  bin:
    output: true
  prj:
    output: true

defaults:
  -
    scope:
      path: ""
      type: "prj"
    values:
      layout: "default"
      comments: true
